top:
   path: /top
   controller: App\Controller\SitesController::top
profilemethod:
   path: /profilemethod
   controller: App\Controller\UIcontroller::profilemethod
profile:
   path: /profile
   controller: App\Controller\SitesController::profile
category:
   path: /category/{id}
   controller: App\Controller\SitesController::category
categories:
   path: /categories
   controller: App\Controller\SitesController::categories
checkscorepsychotest:
   path: quizplay/checkscorepsychotest/{score}/{id}
   controller: App\Controller\PsychotestController::checkscorepsychotest
EditQPMethod:
   path: /EditQPMethod
   controller: App\Controller\PsychotestController::EditQPMethod
editquestionpsychotest:
   path: /editquestionpsychotest/{id}
   controller: App\Controller\SitesController::editquestionpsychotest
deletequestionpsychotest:
   path: /deletequestionpsychotest/{id}
   controller: App\Controller\PsychotestController::deletequestionpsychotest
addquestionpsychotest:
   path: /addquestionpsychotest
   controller: App\Controller\PsychotestController::addquestionpsychotest
editresultspsychotest:
   path: /editresultspsychotest
   controller: App\Controller\PsychotestController::editresultspsychotest
addresultspsychotest:
   path: /addresultspsychotest
   controller: App\Controller\PsychotestController::addresultspsychotest
deletequiz:
   path: /deletequiz/{quizid}
   controller: App\Controller\UIcontroller::deletequiz
search:
   path: /search
   controller: App\Controller\SitesController::search
realeditresultsmethod:
   path: /realeditresultsmethod
   controller: App\Controller\UtilityController::realeditresultsmethod
editresultsmethod:
   path: /editresultsmethod
   controller: App\Controller\UtilityController::editresultsmethod
editresults:
   path: /editresults/{id}
   controller: App\Controller\SitesController::editresults
editquestionmethod:
   path: /editquestionmethod
   controller: App\Controller\UtilityController::editquestionmethod
addquestionmethod:
   path: /addquestionmethod
   controller: App\Controller\UtilityController::addquestionmethod
editquestion:
   path: /editquestion/{id}
   controller: App\Controller\SitesController::editquestion
editquestions:
   path: /editquestions/{id}
   controller: App\Controller\SitesController::editquestions
editquizmethod:
   path: /editquizmethod
   controller: App\Controller\UIcontroller::editquizmethod
editquiz:
    path: /editquiz/{id}
    controller:   App\Controller\SitesController::editquiz
dashboard:
    path: /dashboard
    controller:   App\Controller\SitesController::dashboard
checkscore:
   path: quizplay/checkscore/{score}/{id}
   controller: App\Controller\UIcontroller::checkscore
afterregister:
    path: /afterregister
    controller:   App\Controller\SitesController::afterregister
registermethod:
    path: /registermethod
    controller: App\Controller\SecurityController::registermethod
index:
   path: /
   controller: App\Controller\SitesController::index
createquizmethod:
   path: /createquizmethod
   controller: App\Controller\UIcontroller::createquizmethod
createquiztype:
   path: /createquiztype
   controller: App\Controller\SitesController::createquiztype
checkuser:
   path: /checkuser/{username}
   controller: App\Controller\UIcontroller::checkuser
create_knowledge_test:
   path: /create_knowledge_test
   controller: App\Controller\SitesController::create_knowledge_test
checkemail:
   path: /checkemail/{email}
   controller: App\Controller\UIcontroller::checkemail
quiz:
    path: /quiz/{id}
    controller: App\Controller\SitesController::quiz
quizplay:
    path: /quizplay/{id}
    controller: App\Controller\SitesController::quizplay
deletequestion:
   path: /deletequestion/{id}
   controller: App\Controller\UtilityController::deletequestion









